### ISSUE TITLE
SVG Logo several times larger than original

### ISSUE THREAD

**Issue by lsacher** [gildas-lormeau/SingleFile#657]
The Anaplan.com SVG logo is saved at a much larger size than it should be.

See page and attachment:
https://community.anaplan.com/t5/Anaplan-Platform/Installing-M2Crypto-Python-Library-on-Windows-Machine-for/m-p/79950#M17164

Thanks for the well-thought-out and excellent add-on.
Larry

[Solved_ Re_ Installing M2Crypto Python Library on Windows ... - Page 2 - Anaplan Community (4_12_2021 4_11_29 PM).html.zip](https://github.com/gildas-lormeau/SingleFile/files/6299565/Solved_.Re_.Installing.M2Crypto.Python.Library.on.Windows.-.Page.2.-.Anaplan.Community.4_12_2021.4_11_29.PM.html.zip)

**Comment by gildas-lormeau** [comment]
This bug is due to an invalid stylesheet. 

This page includes a stylesheet named [`global-navigation.css`](https://stage.webservices.anaplan.com/global-navigation/1.1.2/global-navigation.css) which begins with the (pretty-printed) content below.

```css
@import url(https://use.typekit.net/mpv7lfl.css);

.gn[data-v-518176b2] {
    font-size: 16px;
    font-family: proxima-nova,Helvetica Neue,Helvetica,Arial,sans-serif;
    background: #fff;
    border-bottom: 1px solid #e6ebf8;
    display: -ms-grid;
    display: grid;
    -ms-grid-columns: 1fr;
    grid-template-columns: 1fr;
    z-index: 10;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    width: 100%
}

[data-v-518176b2] {
    @import"https://use.typekit.net/mpv7lfl.css"
}
```

The problem is that the line `@import"https://use.typekit.net/mpv7lfl.css"` is invalid. It's simply not allowed in CSS to use an `@import` here. The browser ignores this when you display the original URL. However, SingleFile does not know it's invalid and includes the imported stylesheet. This leads to the whole stylesheet being completely broken.
